import {
  aliceSmith,
  amira,
  carlosMartinez,
  davidWu,
  emilyZhao,
  isabellaRossi,
  jamal,
  johnDoe,
  liamConnor,
  maryBrooks,
  mohammed,
  sallyGreen,
  sophieMuller,
} from "../assets";
import { Staff } from "../types";

export const staffData: Staff[] = [
  {
    id: 1,
    name: "Alice Smith",
    role: "Video Producer",
    email: "alice.smith@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-05-11T10:12:00Z",
    driveUsage: "3.5GB",
    device: "MacBook Pro",
    photo: aliceSmith,
    joinedDate: "2025-05-07",
  },
  {
    id: 2,
    name: "John Doe",
    role: "Content Creator",
    email: "john.doe@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-05-10T17:22:00Z",
    driveUsage: "4GB",
    device: "MacBook Air",
    photo: johnDoe,
    joinedDate: "2025-05-07",
  },
  {
    id: 3,
    name: "Mary Brooks",
    role: "Content Creator",
    email: "mary.brooks@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-05-09T17:31:13Z",
    driveUsage: "7GB",
    device: "Windows 11",
    photo: maryBrooks,
    joinedDate: "2025-05-09",
  },
  {
    id: 4,
    name: "Sally Green",
    role: "Marketing Director",
    email: "sally.green@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-03-011T14:33:01Z",
    driveUsage: "6GB",
    device: "MacBook Pro",
    photo: sallyGreen,
    joinedDate: "2020-04-07",
  },
  {
    id: 5,
    name: "David Wu",
    role: "Software Engineer",
    email: "david.wu@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-04-15T09:22:45Z",
    driveUsage: "12GB",
    device: "Dell XPS",
    photo: davidWu,
    joinedDate: "2023-09-12",
  },
  {
    id: 6,
    name: "Amira Hassan",
    role: "Product Manager",
    email: "amira.hassan@brrmedia.co.uk",
    status: "inactive",
    lastLogin: "2025-02-28T18:05:12Z",
    driveUsage: "4GB",
    device: "HP Spectre",
    photo: amira,
    joinedDate: "2019-02-07",
  },
  {
    id: 7,
    name: "Carlos Martinez",
    role: "UX Designer",
    email: "carlos.martinez@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-03-30T11:17:09Z",
    driveUsage: "7GB",
    device: "MacBook Air",
    photo: carlosMartinez,
    joinedDate: "2019-02-07",
  },
  {
    id: 8,
    name: "Emily Zhao",
    role: "Content Strategist",
    email: "emily.zhao@brrmedia.co.uk",
    status: "inactive",
    lastLogin: "2025-04-08T10:43:56Z",
    driveUsage: "3GB",
    device: "Lenovo ThinkPad",
    photo: emilyZhao,
    joinedDate: "2017-11-22",
  },
  {
    id: 9,
    name: "Mohammed Al-Farsi",
    role: "QA Engineer",
    email: "mohammed.farsi@brrmedia.co.uk",
    status: "inactive",
    lastLogin: "2025-01-12T14:21:31Z",
    driveUsage: "2GB",
    device: "Surface Pro",
    photo: mohammed,
    joinedDate: "2021-05-07",
  },
  {
    id: 10,
    name: "Isabella Rossi",
    role: "Sales Manager",
    email: "isabella.rossi@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-03-20T16:14:22Z",
    driveUsage: "8GB",
    device: "MacBook Pro",
    photo: isabellaRossi,
    joinedDate: "2024-01-18",
  },
  {
    id: 11,
    name: "Liam Connor",
    role: "Support Specialist",
    email: "liam.connor@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-05-10T12:11:09Z",
    driveUsage: "5GB",
    device: "Acer Aspire",
    photo: liamConnor,
    joinedDate: "2025-05-07",
  },
  {
    id: 12,
    name: "Sophie Müller",
    role: "HR Partner",
    email: "sophie.muller@brrmedia.co.uk",
    status: "inactive",
    lastLogin: "2025-02-21T08:09:57Z",
    driveUsage: "1GB",
    device: "MacBook Air",
    photo: sophieMuller,
    joinedDate: "2020-08-10",
  },
  {
    id: 13,
    name: "Jamal Njeri",
    role: "Data Analyst",
    email: "jamal.njeri@brrmedia.co.uk",
    status: "active",
    lastLogin: "2025-04-02T19:44:38Z",
    driveUsage: "9GB",
    device: "Dell Latitude",
    photo: jamal,
    joinedDate: "2022-07-01",
  },
];
